# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patent_rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'patent_rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10patent_rag.proto\x12\tpatentrag\"/\n\x0cQueryRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"S\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x18\n\x10source_documents\x18\x02 \x03(\t\x12\x18\n\x10\x63onfidence_score\x18\x03 \x01(\x02\"&\n\x0cIndexRequest\x12\x16\n\x0e\x64irectory_path\x18\x01 \x01(\t\"N\n\rIndexResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1b\n\x13\x64ocuments_processed\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\x97\x01\n\x0cPatentExpert\x12\x42\n\x0b\x41skQuestion\x12\x17.patentrag.QueryRequest\x1a\x18.patentrag.QueryResponse\"\x00\x12\x43\n\x0cIndexPatents\x12\x17.patentrag.IndexRequest\x1a\x18.patentrag.IndexResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patent_rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=31
  _globals['_QUERYREQUEST']._serialized_end=78
  _globals['_QUERYRESPONSE']._serialized_start=80
  _globals['_QUERYRESPONSE']._serialized_end=163
  _globals['_INDEXREQUEST']._serialized_start=165
  _globals['_INDEXREQUEST']._serialized_end=203
  _globals['_INDEXRESPONSE']._serialized_start=205
  _globals['_INDEXRESPONSE']._serialized_end=283
  _globals['_PATENTEXPERT']._serialized_start=286
  _globals['_PATENTEXPERT']._serialized_end=437
# @@protoc_insertion_point(module_scope)
