# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import patent_rag_pb2 as patent__rag__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in patent_rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatentExpertStub(object):
    """The AI Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskQuestion = channel.unary_unary(
                '/patentrag.PatentExpert/AskQuestion',
                request_serializer=patent__rag__pb2.QueryRequest.SerializeToString,
                response_deserializer=patent__rag__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.IndexPatents = channel.unary_unary(
                '/patentrag.PatentExpert/IndexPatents',
                request_serializer=patent__rag__pb2.IndexRequest.SerializeToString,
                response_deserializer=patent__rag__pb2.IndexResponse.FromString,
                _registered_method=True)


class PatentExpertServicer(object):
    """The AI Service definition
    """

    def AskQuestion(self, request, context):
        """Sends a query to the RAG pipeline and gets an answer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexPatents(self, request, context):
        """Admin function to trigger indexing of new patents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatentExpertServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=patent__rag__pb2.QueryRequest.FromString,
                    response_serializer=patent__rag__pb2.QueryResponse.SerializeToString,
            ),
            'IndexPatents': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexPatents,
                    request_deserializer=patent__rag__pb2.IndexRequest.FromString,
                    response_serializer=patent__rag__pb2.IndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'patentrag.PatentExpert', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('patentrag.PatentExpert', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatentExpert(object):
    """The AI Service definition
    """

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patentrag.PatentExpert/AskQuestion',
            patent__rag__pb2.QueryRequest.SerializeToString,
            patent__rag__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexPatents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patentrag.PatentExpert/IndexPatents',
            patent__rag__pb2.IndexRequest.SerializeToString,
            patent__rag__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
